import type { Metadata } from "next";
 import "../../app/globals.css";
import AppLayout from "../../components/AppLayout/AppLayout";

export const metadata: Metadata = {
  title: "Admin Protfolio",
  description: "Generated by shohid",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <AppLayout>
        <main> {children} </main>
        </AppLayout>
      </body>
    </html>
  );
}
